#!/bin/bash

function display_info() {
    local domain="$1"
    local subdomain="$2"
    local subdomains=("www" "lb-01" "web-01" "web-02")

    if [[ -z "$subdomain" ]]; then
        for sub in "${subdomains[@]}"; do
            info=$(dig +short "$sub.$domain" | awk '{ print $1 }')
            record_type=$(dig +short "$sub.$domain" | awk '{ print $4 }')
            echo "The subdomain $sub is a $record_type record and points to $info"
        done
    else
        info=$(dig +short "$subdomain.$domain" | awk '{ print $1 }')
        record_type=$(dig +short "$subdomain.$domain" | awk '{ print $4 }')
        echo "The subdomain $subdomain is a $record_type record and points to $info"
    fi
}

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain="$1"
subdomain="$2"

display_info "$domain" "$subdomain"

