#!/bin/bash

# Check if all required parameters are provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking for scp
export "SCP_OPTIONS=-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$ssh_key_path" $SCP_OPTIONS "$file_path" "$username@$server_ip:~/"

# Check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer completed successfully!"
else
    echo "File transfer failed!"
fi

